# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"korniatfm.GaussianBlur": "4B. Receptive fields.ipynb",
         "train": "1. Pretrain BarlowTwins.ipynb",
         "defaults.device": "2. Extract features.ipynb",
         "extract_features": "2. Extract features.ipynb",
         "nn_sort": "3. Sort images.ipynb",
         "sort_images": "3. Sort images.ipynb",
         "resize_image": "A. Downsize images.ipynb",
         "resize_images": "A. Downsize images.ipynb",
         "downsize_images": "A. Downsize images.ipynb"}

modules = ["pretrain.py",
           "extract_features.py",
           "sort_images.py",
           "explore_features.py",
           "receptive_fields.py",
           "downsize_images.py"]

doc_url = "https://jpc.github.io/qa_backend/"

git_url = "https://github.com/jpc/qa_backend/tree/main/"

def custom_doc_links(name): return None
